version: 2.1
jobs:
  build:
    machine:
      docker_layer_caching: true
    steps:
      - checkout
      - run:
          name: Instalacja zależności
          command: make deps
      - run:
          name: Uruchomienie Lintera
          command: make lint
      - run:
          name: Uruchomienie Testów
          command: make test
      - run:
          name: Budowanie obrazu Docker
          command: make docker_build
      - run:
          name: Wysłanie obrazu do Docker Hub
          command: |
            echo "$DOCKER_PASSWORD" | docker login -u "$USERNAME" --password-stdin
            make docker_push
            docker logout || tru