version: 2.1
jobs:
  build:
    docker:
      - image: cimg/python:3.13
    steps:
      - checkout
      - run:
          name: Instalacja zależności
          command: make deps
      - run:
          name: Uruchomienie Lintera
          command: make lint
      - run:
          name: Uruchomienie Testów
          command: make test